// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owdfuokwxtzilpptsxrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93ZGZ1b2t3eHR6aWxwcHRzeHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjUzNDMsImV4cCI6MjA2OTgwMTM0M30.sNKUA8scj7ZBv6LHydq47g4aspqCT-Brp0lKssEBnWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});